"""Add created_by to User

Revision ID: 962467e29b35
Revises: fe582513e652
Create Date: 2025-08-21 14:31:53.666884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962467e29b35'
down_revision = 'fe582513e652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
