"""Remove department_id from customers

Revision ID: fe582513e652
Revises: 6ad0864bb012
Create Date: 2025-08-11 12:14:46.388405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe582513e652'
down_revision = '6ad0864bb012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
